### ISSUE TITLE
Loan Reassignment 

### ISSUE THREAD

**Issue by dex2dot0** [zacksharkey/CommunityPlugin#1]
![image](https://user-images.githubusercontent.com/72662496/151648443-9ff976c4-e6dc-4835-ba55-11a829bb3e44.png)

Receiving the above error while attempting to use Loan Reassignment functionality. 

**Persona(s) of user:** Super Admin

**Steps to reproduce:**

1. Right click loan on pipeline
2. Select Loan Reassignment
3. Error occurs

**Comment by zacksharkey** [comment]
Good stuff, I will take a look today thanks Cliff :)

**Comment by zacksharkey** [comment]
#6564802e84d789b97b62768e09665e4941c08fad

**Comment by zacksharkey** [comment]
Fixed in commit 6564802e84d789b97b62768e09665e4941c08fad

**Comment by dex2dot0** [comment]
Thanks @zacksharkey!
