### ISSUE TITLE
Rule Locks

### ISSUE THREAD

**Issue by dex2dot0** [zacksharkey/CommunityPlugin#2]
There may be a lack of documentation around this feature. 

**Expectation:** 
Clicking on Lock Rule checkbox should save

**Observation:**
After clicking on Lock Rule checkbox and entering data in textbox, the lock is not saved:

![image](https://user-images.githubusercontent.com/72662496/151649370-70d35f1a-3849-4a64-9757-5321a6fc0bf0.png)

After saving and opening the business rule again:

![image](https://user-images.githubusercontent.com/72662496/151649375-a29b9f8a-73ef-4c22-b8e1-725f64dee7b3.png)

**Comment by zacksharkey** [comment]
@dex2dot0 This one is okay, its working fine just not documented well. When you save the rule with Lock Rule checked it attempts to send a dataexchange to user lockrule who would be signed into which ever environments you wanted to lock.
