### ISSUE TITLE
AutoMailer Error

### ISSUE THREAD

**Issue by dex2dot0** [zacksharkey/CommunityPlugin#4]
This might be a duplicate of #3 but unsure. After enabling this feature in Plugin Management, ran in to the following errors on next login after selecting the Plugin Management menu in the Encompass menu > Community Menu > AutoMailer:

 **1st Error**
![image](https://user-images.githubusercontent.com/72662496/156867115-e8c9210d-a1c7-445e-b31c-b1941cdc78a4.png)

**2nd Error after clicking OK**
![image](https://user-images.githubusercontent.com/72662496/156867124-d212ebea-b73c-4b41-81e6-92720d1f1b7e.png)

**Comment by zacksharkey** [comment]
This requires you to have a "AutoMailer" folder in your top level reporting structure.
