### ISSUE TITLE
Encompass Settings > Community Plugin > Plugin Management > Configuration Button

### ISSUE THREAD

**Issue by dex2dot0** [zacksharkey/CommunityPlugin#5]
This button does not seem to be doing anything in many scenarios. Tested in a several scenarios it seems like it is not tied to many actions but seems to be present nonetheless:

![image](https://user-images.githubusercontent.com/72662496/156867503-0f18872c-9c31-4a2b-9dc5-efedf5562f42.png)

I tested pushing the button with many options selected and in seemingly most cases it does nothing. In some cases it has the following feedback:

![image](https://user-images.githubusercontent.com/72662496/156867562-42f8b0d2-c139-40eb-a7eb-63acdc4fc3c4.png)

And in some other cases it does indeed activate a sub-menu as expected such as with RetrieveDocuments which pops up the following:

![image](https://user-images.githubusercontent.com/72662496/156867700-aeff13ee-c58f-482c-b63b-de817a406152.png)

All in all I found that selecting the following for the dropdown value for Plugin and pressing the Configuration button resulted in:

- AlphaAlerts = **Nothing**
- AppraiserDialog = **Nothing**
- AutomateInputFormSet = **Nothing**
- Automator = **Nothing**
- BackAndForward = **Nothing**
- DisableServices = **Nothing**
- Doorbell = popup menu
- eFolderTransfer = popup menu
- Example = **Nothing**
- ExportServicePlugin = popup menu
- GridSearch = **Nothing**
- HCAutomate = **Nothing**
- InputFormBuilder_Form = **Nothing**
- KickEveryoneOut = **Nothing**
- LiveTestUser = **Nothing**
- LoanCount = **Nothing**
- LoanFolderMoveTool = popup menu
- MIPTool = **Nothing**
- OpeneFolderDocument = **Nothing**
- OpenInputForm = **Nothing**
- OpenReadOnly = **Nothing**
- PipelineAdvancedSearch = **Nothing**
- PipelineColor = **Nothing**
- PrintFormToEfolder = **Nothing**
- Reassign = **Nothing**
- RetrieveDocuments = popup menu
- RuleLock = **Nothing**
- ServiceNotification = **Nothing**
- ShowColumnField = **Nothing**
- SideMenu = **Nothing**
- TestPlugin = **Nothing**
- TopMenuBase = **Nothing**
- VIP = **Nothing**
- VirtualFields = **Nothing**
- AdvancedSearchForm = "Did not find any configuration for this plugin"
- AnalysisTool = "Did not find any configuration for this plugin"
-  AutoMailer = "Did not find any configuration for this plugin"
- BatchTool = "Did not find any configuration for this plugin"
- Impersonate = "Did not find any configuration for this plugin"
- PipelineViewTransfer = "Did not find any configuration for this plugin"
- PluginManagement = "Did not find any configuration for this plugin"
- SettingExtract = "Did not find any configuration for this plugin"
- FieldLookup = "Did not find any configuration for this plugin"
- LinksAndResources = "Did not find any configuration for this plugin"
- LoanInformation = "Did not find any configuration for this plugin"

**Comment by zacksharkey** [comment]
I have added a message in the base Plugin class to prompt the user when there is no configuration file for plugins "(name of plugin) does not have a configuration file."
