### ISSUE TITLE
AlphaAlerts settings are not saving

### ISSUE THREAD

**Issue by dex2dot0** [zacksharkey/CommunityPlugin#6]
# Issue

When I go in to the PluginManagement menu and configure AlphaAlerts and hit save, the changes are not sticking, or they are at least not showing as sticking in this menu. 

# Root Cause

The CommunityPlugin.json CDO appears to save what I initially save for the configuration of All Access, Personas, or UserIDs but when launching the PluginManagement menu, it does not appear that this is properly read and applied. Thus each change overwrites the previous and each time the PluginManagement menu is launched it shows as though no configuration has been setup. 

## Expectation

When opening the PluginManagement menu and checking one of the given options for All Access, Personas, or Users, I expect that the settings will save and the next time the PluginManagement menu is launched, the same settings should be reflected. 

## Example

When opening the PluginManagement menu and checking one the given options, for example:

![image](https://user-images.githubusercontent.com/72662496/159102884-26ac9ce1-3a50-4a0d-b804-c0275b04f651.png)

### Save Confirmation

![image](https://user-images.githubusercontent.com/72662496/159102973-f1f01c9a-24f0-4b86-b3b8-9dcee72f084a.png)

## Actual Results

After completing the example steps above, logging out of Encompass, and logging back in, I see the following in the PluginManagement menu when AlphaAlerts is selected as the plugin:

![image](https://user-images.githubusercontent.com/72662496/159103049-ea39bc61-3a6e-499e-b98c-e32a2600bd9e.png)

### Additional Notes

This is true whether I select All Access, a Persona, or an individual user.

**Comment by zacksharkey** [comment]
Thanks Cliff, it appears this issue is just that on load the PluginManager is not selecting the first item in the list.

**Comment by zacksharkey** [comment]
Fixed
